
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:

    docker:
      # choose the right version, which include the maven, otherwise the mvn deploy will fail
      - image: cimg/android:2023.02


    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "./build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies


      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "./build.gradle" }}

      # Build
      - run: ./gradlew clean assemble


      # run tests
      - run:
          name: run tests
          command: ./gradlew test

      - run:
          name: Authenticate with GitHub Packages
          command: |
            echo $GITHUB_TOKEN 
            echo $GITHUB_USERNAME

      #run mvn
      - run:
          name: run mvn
          command: |
            mvn clean deploy

      # Invoke jobs via workflows
      # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
      #workflows:
      #android-library-workflow:
      #jobs:
      # - android-library